---
version: "3.8"

volumes:
  data:

services:
  weewx:
    build:
      args:
        - VERSION=4.3.0
      context: .
      dockerfile: Dockerfile
    image: felddy/weewx:4.3.0
    init: true
    restart: "no"
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - TIMEZONE=US/Eastern
      - WEEWX_UID=weewx
      - WEEWX_GID=dialout
