---
name: release

on:
  release:
    types: [prereleased, released]

env:
  IMAGE_NAME: felddy/weewx
  DOCKER_PW: ${{ secrets.DOCKER_PW }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  PLATFORMS: "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,\
    linux/arm64,linux/ppc64le,linux/s390x"
  RUN_TMATE: ${{ secrets.RUN_TMATE }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Determine image version
        id: get_ver
        run: |
          echo "##[set-output name=version;]$(./bump_version.sh show)"
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Log into docker registry
        run: docker login --username "$DOCKER_USER" --password "$DOCKER_PW"
      - name: Build Docker images, tag, and publish
        run: |
          IFS='.' read -r -a version_array \
            <<< "${{ steps.get_ver.outputs.version }}"
          docker buildx build \
            --platform $PLATFORMS \
            --output "type=image,push=true" \
            --tag "$IMAGE_NAME:latest" \
            --tag "${IMAGE_NAME}:${{ steps.get_ver.outputs.version }}" \
            --tag "${IMAGE_NAME}:${version_array[0]}.${version_array[1]}" \
            --tag "${IMAGE_NAME}:${version_array[0]}" \
            --build-arg GIT_COMMIT=$(git log -1 --format=%H) \
            --build-arg GIT_REMOTE=$(git remote get-url origin) \
            --build-arg VERSION=${{ steps.get_ver.outputs.version }} \
            .
      - name: Publish README.md to Docker Hub
        run: ./push_readme.sh
      - name: Setup tmate debug session
        uses: mxschmitt/action-tmate@v1
        if: env.RUN_TMATE
